# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

services:
  backend:
    build:
      context: .
    ports:
      - 8000:8000
  clientapp:
    build: ./clientapp
    ports:
      - 3000:3000
